### ISSUE TITLE
Typo causes pulldown issues in D8 theme

### ISSUE THREAD

**Issue by seattlehimay** [uw-drupal/uw_boundless#14]
There is a typo in templates/menu--main.html.twig on line 35 that causes the menu to appear oddly and poorly styled.
currently:     set drop_downclasses = [
should be:    set dropdown_classes = [

After fixing this, there is a slight misalignment in the menu that can be overridden with:
.dawgdrops-menu {
    left: inherit;
    **top: 55px;**
}
in header.less file.

**Comment by jvogtuw** [comment]
Fixed by boren-uw.
