### ISSUE TITLE
Footer social icon updates

### ISSUE THREAD

**Issue by lcaple** [uw-drupal/uw_boundless#15]
We were recently dinged by Google our YouTube footer icon not adhering to their new brand standards. [We've updated the icon in the svg sprite sheet for uw-2014](https://github.com/uweb/uw-2014/blob/master/assets/svg/uw-sprite.svg). 

Anyone using the old icon can have any of their use of the YouTube API at risk for being out of compliance.

There is also no longer a maintained tumblr account and [it has been removed from the uw-2014 footer](https://github.com/uw-drupal/uw_boundless/blob/master/templates/includes/uw-footer.inc).

**Comment by druliner** [comment]
Updated the css/assets/svg/uw-sprites.svg and removed the tumble link from the README.md file (which manually gets copied / pasted into the footer block in the drupal9 branch).
