### ISSUE TITLE
Links identified only by color

### ISSUE THREAD

**Issue by jvogtuw** [uw-drupal/uw_boundless#3]
Per SiteImprove analysis: color is the only distinguishing feature about links in blocks of text.

Two options:
1) Provide other visual cues (bold or underline)
2) Provide 3:1 contrast ratio with surrounding text.

I prefer the second option. Will look into changing the link text color.

**Comment by jvogtuw** [comment]
The following colors are the lightest gray (body text) and darkest blue (link text) that preserve the required contrast between text and background (4.5:1) and link text and surrounding text (3:1).

body text: #262626 (currently #3D3D3D)
link text: #007ECC (currently #0074BB)

**Comment by jvogtuw** [comment]
Alternatively, a font-weight of 500 on links passes the tests and allows us to keep the same colors. I don't hate it.

**Comment by heatherwoz** [comment]
I don't think the colors should stray too far from what is used in the Wordpress theme. Sites using this theme should visually match those. I wonder if this is something they would like to address too?

**Comment by jvogtuw** [comment]
Good point and I agree. I'll create an issue on their repo, too.

As a side note, the [Accessibility site](https://www.washington.edu/accessibility/web/) added underlines to their links. It's accessible, but it doesn't look great, especially in the menus (IMO).

**Comment by jvogtuw** [comment]
Oh, it looks like the WP theme [added the link underlines](https://github.com/uweb/uw-2014/commit/be09796f638eb80d919798f130a8e2e58a6ceb07) in December. I guess that settles it?

**Comment by heatherwoz** [comment]
It may be a bit of a compromise, but if that's how they solved it, I think you should do the same.

**Comment by jvogtuw** [comment]
Yep

**Comment by jvogtuw** [comment]
Added a bottom border to links in body content. See commit [a98d68c](https://github.com/uw-drupal/uw_boundless/commit/a98d68c42e35bf95c4bc0331b2acf3d370aa510d).
